WebApplication1/Models/Tareas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiAgenda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Tareas
    {
        public int tarea_id { get; set; }
        [DisplayName("Titulo")]
        public string titulo { get; set; }
        [DisplayName("Estado")]
        public bool estado { get; set; }
        public int lista_id { get; set; }
    
        public virtual ListasTareas ListasTareas { get; set; }
    }
}

WebApplication1/Controllers/TareasController.cs
using MiAgenda.Models;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace MiAgenda.Controllers
{
    public class TareasController : Controller
    {
        private BDCalendarioChatEntities db = new BDCalendarioChatEntities();

        // GET: Tareas
        public ActionResult Index(int lista_id)
        {
            //Cuando accedemos poniendo la url a mano
            //if(Session["lista"] == null && lista_id == 0)
            //{
            //    return new HttpUnauthorizedResult();
            //}
            //
            //else if(lista_id == 0)
            //{
            //    lista_id = (Session["lista"] as ListasTareas).lista_id;
            //}
            var tareas = db.Tareas.Include(t => t.ListasTareas).Where(x => x.lista_id == lista_id).ToList();

            Session["lista"] = db.ListasTareas.Find(lista_id);

            return View(tareas);
        }

        // GET: Tareas/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Tareas tareas = db.Tareas.Find(id);
        //    if (tareas == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tareas);
        //}

        // GET: Tareas/Create
        public ActionResult Create()
        {
            ViewBag.lista_id = new SelectList(db.ListasTareas, "lista_id", "nombre");
            return View();
        }

        // POST: Tareas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "tarea_id,titulo,estado,lista_id")] Tareas tareas)
        {
            if (ModelState.IsValid)
            {
                tareas.lista_id = (Session["lista"] as ListasTareas).lista_id;
                db.Tareas.Add(tareas);
                db.SaveChanges();
                return RedirectToAction("Index", new { tareas.lista_id });
            }

            //ViewBag.lista_id = new SelectList(db.ListasTareas, "lista_id", "nombre", tareas.lista_id);
            return View(tareas);
        }

        // GET: Tareas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tareas tareas = db.Tareas.Find(id);
            if (tareas == null)
            {
                return HttpNotFound();
            }
            ViewBag.lista_id = new SelectList(db.ListasTareas, "lista_id", "nombre", tareas.lista_id);
            return View(tareas);
        }

        // POST: Tareas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "tarea_id,titulo,estado,lista_id")] Tareas tareas)
        {
            if (ModelState.IsValid)
            {
                tareas.lista_id = (Session["lista"] as ListasTareas).lista_id;
                db.Entry(tareas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", tareas.lista_id);
            }
            ViewBag.lista_id = new SelectList(db.ListasTareas, "lista_id", "nombre", tareas.lista_id);
            return View(tareas);
        }

        // GET: Tareas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tareas tareas = db.Tareas.Find(id);
            if (tareas == null)
            {
                return HttpNotFound();
            }
            return View(tareas);
        }

        // POST: Tareas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tareas tareas = db.Tareas.Find(id);
            db.Tareas.Remove(tareas);
            db.SaveChanges();
            return RedirectToAction("Index", tareas.lista_id);
        }

        // POST: Tareas/Done/5
        [HttpGet]
        public ActionResult Done(int id)
        {
            try
            {
                var tarea = db.Tareas.Find(id);
                tarea.estado = !tarea.estado;
                db.Entry(tarea).State = EntityState.Modified;
                db.SaveChanges();
                int lista_id = tarea.ListasTareas.lista_id;
                return RedirectToAction("Index", new { lista_id = lista_id });
                //return new HttpStatusCodeResult(200);
            }
            catch
            {
                return new HttpStatusCodeResult(500);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Tareas/Create.cshtml
@model MiAgenda.Models.Tareas

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Login.css" rel="stylesheet" />

@using (Html.BeginForm("Create", "Tareas", FormMethod.Post, new { @class = "border border-warning" }))
{
    <div class="titulo">
        <h2 class="text-warning">Nueva tarea</h2>
    </div>
    <hr />
    <div id="content" class="m-3">
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group row">
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control", autocomplete = false, placeholder = "Nombre de la tarea" } })
                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
            </div>
            @if (ViewBag.error != null)
            {
                <p class="text-danger">@ViewBag.error</p>
            }
            <div class="container-fluid">
                <div class="row">
                    <div class="mx-auto">
                        <div class="volverInicio">
                            <a class="btn btn-light" href="@Url.Action("Index", "ListasTareas")">Volver a las listas</a>
                        </div>
                        <div class="btnEntrar ml-1">
                            <input type="submit" value="Crear" class="btn btn-warning" id="btnSubmit" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

WebApplication1/Views/Tareas/Delete.cshtml
@model MiAgenda.Models.Tareas

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tareas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ListasTareas.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ListasTareas.nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Tareas/Details.cshtml
@model MiAgenda.Models.Tareas

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Tareas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ListasTareas.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ListasTareas.nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.tarea_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/Views/Tareas/Edit.cshtml
@model MiAgenda.Models.Tareas

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Login.css" rel="stylesheet" />

@using (Html.BeginForm())
{
    <h2 class="text-warning">Editando tarea</h2>
    <hr />
    <div id="content">
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.tarea_id)
            <div class="form-group">
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control", placeholder = "Titulo" } })
                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
            </div>
            @if (ViewBag.error != null)
            {
                <p class="text-danger">@ViewBag.error</p>
            }
            <div class="container-fluid">
                <div class="row">
                    <div class="mx-auto">
                        <div class="volverInicio">
                            <a class="btn btn-light" href="@Url.Action("Index", new { lista_id = Model.lista_id })">Volver a las tareas</a>
                        </div>
                        <div class="btnEntrar ml-1">
                            <input type="submit" value="Guardar" class="btn btn-warning" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

WebApplication1/Views/Tareas/Index.cshtml
@model IEnumerable<MiAgenda.Models.Tareas>
@using System.Text.RegularExpressions
@using MiAgenda.Models
@{
    ViewBag.Title = "Lista " + (Session["lista"] as ListasTareas).nombre;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/IndexCalendario.css" rel="stylesheet" />
@{
    string uAg = Request.ServerVariables["HTTP_USER_AGENT"];
    Regex regEx = new Regex(@"android|iphone|ipad|ipod|blackberry|symbianos", RegexOptions.IgnoreCase);
    bool isMobile = regEx.IsMatch(uAg);

    if (isMobile)
    {
        <div class="text-center">
            <h2>Tareas de @((Session["lista"] as ListasTareas).nombre)</h2>
            <a class="btn btn-light" href="@Url.Action("Index", "ListasTareas")">Volver a las listas</a>
            @Html.ActionLink("Crear tarea", "Create", null, new { @class = "btn btn-warning" })
        </div>
    }
    else
    {
        <h2 class="text-center">Tareas de @((Session["lista"] as ListasTareas).nombre)</h2>
        <div class="bg-white">
            <div class="row m-1">
                <a class="btn btn-light ml-auto" href="@Url.Action("Index", "ListasTareas")">Volver a las listas</a>
                @Html.ActionLink("Crear tarea", "Create", null, new { @class = "btn btn-warning" })
            </div>
        </div>
    }
}

@if (Model != null && Model.Count() != 0)
{
    <table class="table table-striped table-borderless text-center border border-warning rounded-bottom">
        <tr>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.titulo)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.estado)
            </th>
            <th class="text-center">
                Acciones
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td class="m-auto">
                    @Html.DisplayFor(modelItem => item.titulo)
                </td>
                <td class="m-auto">
                    @Html.ActionLink(item.estado ? "✔ " + "Marcar como Pendiente" : "✗ " + "Marcar como Hecho", "Done", "Tareas", new { id = item.tarea_id }, new { @class = item.estado ? "btn btn-success" : "btn btn-danger" })
                </td>
                <td class="m-auto">
                    <a id="@item.tarea_id" href="@Url.Action("Edit", "Tareas", new { id = item.tarea_id })">Editar</a>
                </td>
            </tr>
        }
    </table>
}
else
{
    <h4 class="text-center">No hay tareas.</h4>
}