WebApplication1/Models/Calendarios.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiAgenda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Calendarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calendarios()
        {
            this.CalendariosUsuariosSet = new HashSet<CalendariosUsuariosSet>();
            this.Eventos = new HashSet<Eventos>();
        }
    
        public int calendario_id { get; set; }
        [DisplayName("Nombre")]
        public string nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalendariosUsuariosSet> CalendariosUsuariosSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eventos> Eventos { get; set; }
    }
}

WebApplication1/Controllers/CalendariosController.cs
using MiAgenda.Filters;
using MiAgenda.Models;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Metadata.Edm;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web.Mvc;

namespace MiAgenda.Controllers
{
    [AutorizadoFilter]
    public class CalendariosController : Controller
    {
        /*delete from Tareas;
        delete from ListasTareas;
        delete from ListasTareasUsuariosSet;
        delete from Eventos;
        delete from CalendariosUsuariosSet;
        delete from Calendarios;
        delete from Usuarios;
        DBCC CHECKIDENT('Usuarios', RESEED, 0);*/

        private readonly BDCalendarioChatEntities db = new BDCalendarioChatEntities();
        //private CalendariosService calendariosService;

        public CalendariosController()
        {
            //calendariosService = new CalendariosService();
        }

        // GET: Calendarios
        public ActionResult Index()
        {
            var usuario = Session["userMiAgenda"] as Usuarios;

            // Consultando a webapi
            //var calendarios = calendariosService.GetCalendarios(usuario);

            var calendarios = db.CalendariosUsuariosSet.Where(x => x.user_id == usuario.user_id).Select(x => x.Calendarios).ToList();
            return View(calendarios);
        }

        // GET: Calendarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Calendarios calendarios = db.Calendarios.Find(id);
            if (calendarios == null)
            {
                return HttpNotFound();
            }
            return View(calendarios);
        }

        // GET: Calendarios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Calendarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Calendarios calendarios)
        {
            //Comprobamos si el usuario tiene un calendario con ese mismo nombre
            var usuario = Session["userMiAgenda"] as Usuarios;
            var calendariosUsuario = db.CalendariosUsuariosSet.Where(x => x.user_id == usuario.user_id).Select(x => x.Calendarios).ToList();

            var cal = calendariosUsuario.Where(x => x.nombre == calendarios.nombre.ToUpper()).ToList();
            if (cal.Count() > 0)
            {
                ViewBag.error = "Ya tienes un calendario con ese nombre.";
                return View();
            }

            if (ModelState.IsValid)
            {
                //db.Usuarios.Attach(usuario);
                //calendarios.Usuarios.Add(usuario);

                calendarios.CalendariosUsuariosSet.Add(new CalendariosUsuariosSet()
                {
                    calendario_id = calendarios.calendario_id,
                    user_id = usuario.user_id,
                    creador = true
                });
                calendarios.nombre = calendarios.nombre.ToUpper();

                db.Calendarios.Add(calendarios);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(calendarios);
        }

        // GET: Calendarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Calendarios calendarios = db.Calendarios.Find(id);
            if (calendarios == null)
            {
                return HttpNotFound();
            }
            return View(calendarios);
        }

        // POST: Calendarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "calendario_id,nombre")] Calendarios calendarios)
        {
            if (ModelState.IsValid)
            {
                db.Entry(calendarios).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(calendarios);
        }

        // GET: Calendarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Calendarios calendarios = db.Calendarios.Find(id);
            if (calendarios == null)
            {
                return HttpNotFound();
            }
            return View(calendarios);
        }

        // POST: Calendarios/DeleteCalendar/5
        [HttpPost]
        public ActionResult DeleteCalendar(int id)
        {
            var usuario = Session["userMiAgenda"] as Usuarios;
            Calendarios calendarios = db.Calendarios.Find(id);
            CalendariosUsuariosSet calUsu = db.CalendariosUsuariosSet.Find(id, usuario.user_id);

            if (calUsu.creador)
            {
                db.Calendarios.Remove(calendarios);
                db.SaveChanges();
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        // POST: Calendarios/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Calendarios calendarios = db.Calendarios.Find(id);
            db.Calendarios.Remove(calendarios);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AddUserToCalendar(int calendario_id, string emailUsuarioNuevo)
        {
            if (!Regex.IsMatch(emailUsuarioNuevo, @"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?"))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var usuarioInvitado = db.Usuarios.Where(x => x.email == emailUsuarioNuevo).FirstOrDefault();
            if (usuarioInvitado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            var existeCalendario = db.CalendariosUsuariosSet.Where(x => x.calendario_id == calendario_id && x.user_id == usuarioInvitado.user_id).FirstOrDefault();
            if (existeCalendario != null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Ambiguous);
            }

            var calendario = db.Calendarios.Find(calendario_id);
            db.CalendariosUsuariosSet.Add(new CalendariosUsuariosSet()
            {
                creador = false,
                user_id = usuarioInvitado.user_id,
                calendario_id = calendario.calendario_id
            });
            db.SaveChanges();

            var usuarioInvitador = Session["userMiAgenda"] as Usuarios;
            EmailUtility.MandarCorreo(usuarioInvitado, usuarioInvitador, calendario);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult RemoveUserFromCalendar(int calendario_id, int user_id)
        {
            //falta comprobar  que el que elimina es el creador, por si acaso
            var calendario = db.Calendarios.Find(calendario_id);
            if(calendario == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "El calendario no existe.");
            }
            var calendarioUsuario = calendario.CalendariosUsuariosSet.FirstOrDefault(x => x.user_id == user_id);
            if (calendarioUsuario == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "El usuario no existe.");
            }
            calendario.CalendariosUsuariosSet.Remove(calendarioUsuario);
            db.SaveChanges();

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Calendarios/Create.cshtml
@model MiAgenda.Models.Calendarios

@{
    ViewBag.Title = "Crear formulario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Login.css" rel="stylesheet" />

@using (Html.BeginForm("Create", "Calendarios", FormMethod.Post, new { @class = "border border-warning" }))
{
    <div class="titulo">
        <h2 class="text-warning">Nuevo calendario</h2>
    </div>
    <hr />
    <div id="content" class="m-3">
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group row">
                @*@Html.LabelFor(model => model.usuario, htmlAttributes: new { @class = "control-label col-md-2" })*@
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", placeholder = "Nombre del calendario" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
            @if (ViewBag.error != null)
            {
                <p class="text-danger">@ViewBag.error</p>
            }
            <div class="container-fluid">
                <div class="row">
                    <div class="mx-auto">
                        <div class="volverInicio">
                            <a class="btn btn-light" href="@Url.Action("Index", "Calendarios")">Volver a la lista de calendarios</a>
                        </div>
                        <div class="btnEntrar ml-1">
                            <input type="submit" value="Crear" class="btn btn-warning" id="btnSubmit" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

WebApplication1/Views/Calendarios/Delete.cshtml
@model MiAgenda.Models.Calendarios

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Calendarios</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Calendarios/Details.cshtml
@model MiAgenda.Models.Calendarios

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Login.css" rel="stylesheet" />
@*<br />

    <h3>Usuarios</h3>
    <ul>
        @foreach (var calendarioUsuario in Model.CalendariosUsuariosSet)
        {

            if (!calendarioUsuario.creador)
            {
                <li>
                    @calendarioUsuario.Usuarios.usuario &#128100;
                </li>
            }
            else
            {
                <li>
                    @calendarioUsuario.Usuarios.usuario &#10022;
                </li>
            }
        }
    </ul>
    <p>
        @Html.ActionLink("Volver a la lista de calendarios", "Index", null, new { @class = "btn btn-default" })
    </p>*@

<form class="border border-warning">
    <div class="titulo">
        <h2 class="text-warning">Detalles de @Model.nombre</h2>
    </div>
    <hr />
    <div id="content" class="m-3">
        <div class="form-horizontal">
            <div class="form-group row">
                <h3>Usuarios</h3>
            </div>
            <div class="form-group row">
                <ul>
                    @foreach (var calendarioUsuario in Model.CalendariosUsuariosSet)
                    {

                        if (!calendarioUsuario.creador)
                        {
                            <li>
                                @calendarioUsuario.Usuarios.usuario &#128100;
                            </li>
                        }
                        else
                        {
                            <li>
                                @calendarioUsuario.Usuarios.usuario &#10022;
                            </li>
                        }
                    }
                </ul>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="mx-auto">
                        <div class="volverInicio">
                            <a class="btn btn-light" href="@Url.Action("Index", "Calendarios")">Volver al inicio</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

WebApplication1/Views/Calendarios/Edit.cshtml
@model MiAgenda.Models.Calendarios

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
@*<h2>No disponible</h2>*@

<h3>Usuarios</h3>
<ul>
    @foreach (var calendarioUsuario in Model.CalendariosUsuariosSet)
    {

        if (!calendarioUsuario.creador)
        {
            <li>
                @calendarioUsuario.Usuarios.usuario 
                <a id="@calendarioUsuario.user_id" href="#" onclick="eliminar(@calendarioUsuario.calendario_id, @calendarioUsuario.user_id)">&#x274C;</a>
            </li>
        }
        else
        {
            <li>
                @calendarioUsuario.Usuarios.usuario
            </li>
        }
    }
</ul>

@*<table>
    <thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>*@

@*@using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Calendarios</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.calendario_id)

            <div class="form-group">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }*@

<div>
    @Html.ActionLink("Volver a la lista de calendarios", "Index", null, new { @class = "btn btn-default" })
</div>

<script>
    function eliminar(calendario_id, user_id) {
        $.ajax({
            type: "POST",
            url: "/Calendarios/RemoveUserFromCalendar",
            data: { 'calendario_id': calendario_id, 'user_id': user_id },
            success: function (data) {
                location.reload()
            },
            error: function (error) {
                if (error.status == 404) {
                    $('#txtError').show();
                    $('#txtError').text(error.statusText);
                } else if (error.status == 400) {
                    $('#txtError').show();
                    $('#txtError').text('El email introducido no es valido.');
                } else {
                    alert('error al eliminar al usuario');
                }
            }
        })
    }
</script>

WebApplication1/Views/Calendarios/Index.cshtml
@model IEnumerable<MiAgenda.Models.Calendarios>
@using System.Text.RegularExpressions
@using MiAgenda.Models
@{
    /**/

    /**/

    ViewBag.Title = "Mis calendarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/IndexCalendario.css" rel="stylesheet" />
<br />
@{
    string uAg = Request.ServerVariables["HTTP_USER_AGENT"];
    Regex regEx = new Regex(@"android|iphone|ipad|ipod|blackberry|symbianos", RegexOptions.IgnoreCase);
    bool isMobile = regEx.IsMatch(uAg);

    if (isMobile)
    {
        <div class="text-center mb-2">
            <h2>Mis calendarios</h2>
            @Html.ActionLink("Crear calendario", "Create", null, new { @class = "btn btn-outline-warning" })
        </div>
    }
    else
    {
        <h2 class="text-center">Mis calendarios</h2>
        <div class="bg-white rounded-top">
            <div class="row m-1">
                @*<h2>Mis calendarios</h2>*@
                @Html.ActionLink("Crear calendario", "Create", null, new { @class = "btn btn-warning ml-auto" })
            </div>
        </div>
    }
}


@if (Model != null && Model.Count() != 0)
{
    <table class="table table-striped table-borderless text-center border border-warning">
        <tr>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th class="text-center">
                Acciones
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.nombre, "Home", "Users", new { calendario = item.calendario_id }, null)
                </td>
                <td>
                    @{
                        var calendarioUsuario = item.CalendariosUsuariosSet.Where(x => x.calendario_id == item.calendario_id && (Session["userMiAgenda"] as Usuarios).user_id == x.user_id).FirstOrDefault();
                        <a id="@item.calendario_id" href="@Url.Action("Details", "Calendarios", new { id = item.calendario_id })">Detalles</a>
                        if (calendarioUsuario.creador)
                        {
                            <a id="@item.calendario_id" href="@Url.Action("Edit", "Calendarios", new { id = item.calendario_id })">| Editar</a>
                            <a class="btnEliminar" id="@item.calendario_id" href="#" onclick="eliminar(@item.calendario_id)">| Eliminar</a>
                            <a class="btnInvitar" id="@item.calendario_id" href="#">| Invitar</a>
                        }
                    }
                </td>
            </tr>
        }
    </table>
}
else
{
    <h4>No hay calendarios.</h4>
}

@* Invitar a usuario al calendario *@
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><span id="eventTitle">Invitando</span></h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="txtCalendarioID" />
                @*<label>Email </label>*@
                <input type="text" id="txtEmail" class="form-control" placeholder="Email del invitado" />
                <p class="text-danger" id="txtError"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" id="btnInvitar">Invitar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.btnInvitar').click(function (e) {
            $('#txtCalendarioID').val(this.id);
            $('#txtError').hide();
            $('#txtEmail').val('');
            $('#myModal').modal();
        });
        $('#btnInvitar').click(function (e) {
            var email = $('#txtEmail').val();
            var calendario_id = +$('#txtCalendarioID').val();
            $.ajax({
                type: "POST",
                url: "/Calendarios/AddUserToCalendar",
                data: { 'calendario_id': calendario_id, 'emailUsuarioNuevo': email },
                success: function (data) {
                    $('#myModal').modal('hide');
                },
                error: function (error) {
                    if (error.status == 404) {
                        $('#txtError').show();
                        $('#txtError').text('El email introducido no existe.');
                    } else if (error.status == 400) {
                        $('#txtError').show();
                        $('#txtError').text('El email introducido no es valido.');
                    } else if (error.status == 300) {
                        $('#txtError').show();
                        $('#txtError').text('El usuario con este email ya esta invitado.');
                    } else {
                        alert('failed to invite');
                    }
                }
            })
        });
    });
    function eliminar(id) {
        //alert(id);
        if (confirm("¿Estas seguro/a?")) {
            $.ajax({
                type: "POST",
                url: "/Calendarios/DeleteCalendar/" + id,
                success: function (data) {
                    location.reload()
                },
                error: function (error) {
                    alert(error.responseText);
                }
            })
        }
    }
</script>

WebApplication1/Views/Calendarios/View.cshtml
@model IEnumerable<MiAgenda.Models.Calendarios>

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.calendario_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.calendario_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.calendario_id })
        </td>
    </tr>
}

</table>